{{ $values := .Values}}
{{- if $values.ngcCredentials.password }}

apiVersion: v1
kind: Secret
data:
  apikey: {{ .Values.ngcCredentials.password |  quote }}
metadata:
  creationTimestamp: null
  name: modelpullsecret
  namespace: {{ .Release.Namespace }}
{{- end}}
